vich_uploader:
    db_driver: orm

    # mappings:
    #   property_image:
    #     uri_prefix: /images/dg
    #     upload_destination: '%kernel.project_dir%/public/images/dg'
    #     namer : Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'


    mappings:
      actualite_image:
          uri_prefix: '%uploads_actualite_path%'
          upload_destination: '%kernel.project_dir%/public/%uploads_actualite_path%'

      actualite_attachements:
        uri_prefix: '%uploads_actualite_path%'
        upload_destination: '%kernel.project_dir%/public/%uploads_actualite_path%'

      dg_image:
          uri_prefix: '%dg_image_path%'
          upload_destination: '%kernel.project_dir%/public/%dg_image_path%'

      centre_image:
          uri_prefix: '%centre_image_path%'
          upload_destination: '%kernel.project_dir%/public/%centre_image_path%'
